version: 2
project_name: ligolo-mp

before:
  hooks:
  - make clean
  - make agent

builds:
  - main: ./cmd/server
    id: "server-386"
    binary: server
    env: [CGO_ENABLED=0]
    flags:
      - -trimpath
      - -mod=vendor
    hooks:
      pre:
        - sh -c "TARGET_ARCH=386 make go"
    goos:
      - linux
    goarch:
      - 386

  - main: ./cmd/server
    id: "server-amd64"
    binary: server
    env: [CGO_ENABLED=0]
    flags:
      - -trimpath
      - -mod=vendor
    hooks:
      pre:
        - sh -c "TARGET_ARCH=amd64 make go"
    goos:
      - linux
    goarch:
      - amd64

  - main: ./cmd/server
    id: "server-arm64"
    binary: server
    env: [CGO_ENABLED=0]
    flags:
      - -trimpath
      - -mod=vendor
    hooks:
      pre:
        - sh -c "TARGET_ARCH=arm64 make go"
    goos:
      - linux
    goarch:
      - arm64

  - main: ./cmd/client
    id: "client"
    binary: client
    env: [CGO_ENABLED=0]
    flags:
      - -trimpath
      - -mod=vendor
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - 386
      - amd64
      - arm64

archives:
  - 
    id: "server"
    ids: ['server-386', 'server-amd64', 'server-arm64']
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    formats: ['binary']

  - 
    id: "client"
    ids: ['client']
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    formats: ['binary']

release:
  github:
  disable: false

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
