project_name: ligolo-mp

before:
  hooks:
  - make clean
  - make assets

builds:
  - main: ./cmd/server
    id: "server"
    binary: server
    env: [CGO_ENABLED=0]
    flags:
      - -trimpath
      - -mod=vendor
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
    goarm:
      - 6
      - 7

  - main: ./cmd/client
    id: "client-linux"
    binary: client
    env: [CGO_ENABLED=0]
    flags:
      - -trimpath
      - -mod=vendor
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
    goarm:
      - 6
      - 7

  - main: ./cmd/client
    id: "client-windows"
    binary: client
    env: [CGO_ENABLED=0]
    flags:
      - -trimpath
      - -mod=vendor
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7

archives:
  - 
    id: "server"
    builds: ['server']
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: binary

  - 
    id: "client"
    builds: ['client-linux', 'client-windows']
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: binary

release:
  github:
  disable: false

checksum:
  name_template: "{{ .ArtifactName }}.sig"
  algorithm: sha256
  split: true
  disable: false